import "./globals.css";
import type { Metadata } from "next";

import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "GAIA - CIMMIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Header />
        <main className="bg-red-500 h-[200dvh]">{children}</main>
      </body>
    </html>
  );
}
