import "./globals.css";
import type { Metadata } from "next";

import Header from "@/components/layout/header";

export const metadata: Metadata = {
  title: "GAIA - CIMMYT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
